- hosts: 10.142.0.12
  tasks:
  - name: Java Ubuntu Setup
    when: ansible_pkg_mgr == "apt"
    apt:
      name: openjdk-11-jdk
    become: true

  - name: Java CentOS Setup
    when: ansible_pkg_mgr == "yum"
    yum:
      name: java
    become: true
